---
- hosts: ec2
  gather_facts: no
  tasks:
    - name: Install the Rapid7 Insight Agent
      shell: curl -s https://cloud.rapid7.com/linux/install | bash

    - name: Configure the Rapid7 Insight Agent
      lineinfile:
        path: /etc/rapid7/insight-agent.conf
        regexp: '^#?(api_key=).*'
        line: 'api_key={{ api_key }}'
      vars:
        api_key: YOUR_API_KEY
